apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: discoverlocal
spec:
  storageClassName: local-path  # K3s default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: discoverlocal
spec:
  storageClassName: local-path  # K3s default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi